db_server: maria-db
db_name: pbdb_culled
db_user: root
db_password: mohil123
db_host: 127.0.0.1
output_directory: ./output_dir/
generate_uuid: true # specifies whether to generate uuid from entity_nodes & use them or use table-name_col-name_val as global unigue identifier
entity_node_queries: conf/entity_nodes.txt
edges_entity_entity_queries: conf/edges_entity_entity.txt
edges_entity_feature_values_queries: conf/edges_entity_feature_values.txt
